baseURL = "www.ctpethiopia.org"
languageCode = "en-us"
title = "Counseling and Test Preparation Ethiopia | CTP Ethiopia Inc."
themesDir = "../.."
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "CTP Ethiopia LOGO"

  [params.seo]
    meta_twitter_site = "@ctpethiopia"
    meta_twitter_creator = "@ctpethiopia"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'By CTP Ethiopia Inc. <a class="zerostatic" href="https://www.ctpethiopia.org">www.ctpethiopia.org</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Our Approach"
    url = "/Our Approach/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
