---
label: Service
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: boolean
  name: featured
  label: featured
- type: text
  name: weight
  label: weight
